GET http://localhost:3000/posts

###
POST http://172.16.1.251/pagos/pagos-qr/obtener-qr
Content-Type: application/json

{
  "datos":
  {
    "monto":101,
    "referencia":"pagoOrden-018-3651163",
    "codigoPago":"VEN-018-3651163",
    "nombreCompleto":"JOSE MENDOZA VARGAS",
    "item":{
      "idOrden":"018",
      "nroComprobante":0,
      "fechaPago":"2024-03-04",
      "FechaLimiteAtencion":"06/03/2024"
    }
  }
}

###
http://172.16.1.251/consultasapi/v0/recepcion?codigoPago=123&nroDocumento=123&fechaPago=2024-03-01